# Generated by Django 5.0.3 on 2024-03-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_bookcopy_options_alter_country_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
