# Generated by Django 5.0.3 on 2024-03-29 09:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_bookcopy_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookCopy',
            new_name='BookInstance',
        ),
    ]
